# AUTO-GENERATED by scripts/generate_dims.py — DO NOT EDIT BY HAND.
# Source: Dayshape Reporting Service Detail workbook v26.3.0.
# Regenerate with: python scripts/generate_dims.py

"""Generated report registry data (plan.md §0.4, §3.5).

Consumed by :mod:`dayshape.reports.registry`. Permission strings are kept
verbatim from the workbook, including the known irregularities flagged in
plan.md §11.2 R-1 (e.g. ``Report_UnitListing_Read``).
"""

from __future__ import annotations

# report_id -> (display_name, report_type, permissions, rate_limited)
CATALOGUE: dict[str, tuple[str, str, str, bool]] = {
    'ActualListing': ('Actual Listing', 'Listing', 'Reporting_Read', False),
    'ApprovedBudgetListing': ('Approved Budget Listing', 'Listing', 'Reporting_ApprovedBudgetListing_Read', False),
    'Availability': ('Availability', 'Pivot', 'Reporting_Read and Reporting_Availability_Read', True),
    'AvailabilityPlanning': ('Availability Planning', 'Pivot', 'Reporting_Read and Reporting_AvailabilityPlanning_Read', True),
    'ClashHoursByTime': ('Clash Hours Over Time', 'Pivot', 'Reporting_Read and Reporting_ClashHoursByTime_Read', True),
    'ClientListing': ('Client Listing', 'Listing', 'Reporting_Read and Reporting_ClientListing_Read', False),
    'ComparativeRevenue': ('Comparative Revenue', 'Pivot', 'Reporting_Read and Reporting_ComparativeRevenue_Read Gross Revenue dimension requires at least one of Jobs_Economics_Read_KeyPersonnel, Jobs_Economics_Read_ViewableUnits', True),
    'ConflictHours': ('Conflict Hours Over Time', 'Pivot', 'Reporting_Read and Reporting_ConflictHoursByTime_Read', False),
    'ExchangeRateListing': ('Currency Exchange Rate Listing', 'Listing', 'Reporting_Read and Reporting_ExchangeRateListing_Read', False),
    'JobGroupListing': ('Engagement Group Listing', 'Listing', 'Reporting_Read and Reporting_JobGroupListing_Read', False),
    'JobListing': ('Engagement Listing', 'Listing', 'Reporting_Read and any one of the following: Reporting_JobListing_Read Gantt_Assign Jobs_Create_Any Jobs_Create_EditableUnits Jobs_Create_KeyPersonnel Jobs_PriorYear_Edit', False),
    'JobTaskPhaseListing': ('Job Task Phase Listing', 'Listing', 'Reporting_Read and Report_JobTaskPhaseListing_Read', False),
    'LogListingCustomMember': ('Custom Member Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingCustomMember_Read', False),
    'LogListingGrade': ('Grade Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingGrade_Read', False),
    'LogListingJob': ('Engagement Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingJob_Read', True),
    'LogListingJobGroup': ('Engagement Group Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingJobGroup_Read', True),
    'LogListingSetting': ('Setting Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingSetting_Read', True),
    'LogListingSuggestion': ('Suggestion Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingSuggestion_Read', False),
    'LogListingTask': ('Booking Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingTask_Read', True),
    'LogListingTrait': ('Trait Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingTrait_Read', False),
    'LogListingUnavailability': ('Unavailability Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingUnavailability_Read', True),
    'LogListingUser': ('User Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingUsers_Read', True),
    'LogListingWorker': ('Resource Audit Trail', 'Listing', 'Reporting_Read and Reporting_LogListingWorker_Read', True),
    'LogListingWorkflow': ('Workflow Audit Trail', 'Listing', 'Reporting_Read and Reporting_WorkflowLogListing_Read', False),
    'RateListing': ('RateListing', 'Listing', 'Reporting_Read and Reporting_RateListing_Read', False),
    'RestrictionListing': ('Restriction Listing', 'Listing', 'Reporting_Read and Reporting_RestrictionListing_Read', False),
    'RevenueByTime': ('Revenue Over Time', 'Pivot', 'Reporting_Read and Gross Revenue and Net Revenue dimensions require: Reporting_RevenueByTime_Read and at least one of Jobs_Economics_Read_KeyPersonnel, Jobs_Economics_Read_ViewableUnits', True),
    'ScheduleExport': ('Master Schedule', 'Pivot', 'Reporting_Read and Reporting_ScheduleExport_Read', False),
    'TaskHoursByTime': ('Booking Hours Over Time', 'Pivot', 'Reporting_Read and Reporting_TaskHoursByTime_Read', True),
    'TaskListing': ('Booking Listing', 'Listing', 'Reporting_Read and Reporting_TaskListing_Read', True),
    'TaskVsActualHoursByTime': ('Booking_Actual Hours Over Time', 'Listing', 'Reporting_TaskVsActualHoursByTime_Read', True),
    'TraitListing': ('Trait Listing', 'Listing', 'Reporting_Read and Reporting_TraitListing_Read', False),
    'UnavailabilityHoursByTime': ('Unavailability Hours Over Time', 'Pivot', 'Reporting_Read and Reporting_UnavailabilityHoursByTime_Read', True),
    'UnavailabilityListing': ('Unavailability Listing', 'Listing', 'Reporting_Read and Reporting_UnavailabilityListing_Read', False),
    'UnitListing': ('Unit Listing', 'Listing', 'Reporting_Read and Report_UnitListing_Read', False),
    'UserListing': ('User Listing', 'Listing', 'Reporting_Read and Reporting_UserListing_Read', False),
    'Utilisation': ('Utilisation', 'Pivot', 'Reporting_Read and Reporting_Utilisation_Read', False),
    'WorkerCountByTime': ('Resource Count Over Time', 'Listing', 'Reporting_Read and Reporting_WorkerCountByTime_Read', False),
    'WorkerListing': ('Resource Listing', 'Listing', 'Reporting_Read and Reporting_WorkerListing_Read', False),
    'WorkerPromotionListing': ('Resource Promotion Listing', 'Listing', 'Reporting_Read and Reporting_WorkerPromotionListing_Read', False),
    'WorkerTraitListing': ('Resource Trait Listing', 'Listing', 'Reporting_Read and Reporting_WorkerTraitListing_Read', False),
    'WorkerWorkHours': ('Resource Work Hours', 'Pivot', 'Reporting_Read and Reporting_WorkerWorkHours_Read', True),
}
